; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.x"

; Modules
projects[adaptive_image][version] = "1.4"

projects[backup_migrate][version] = "2.8"

projects[boxes][version] = "1.1"

projects[ctools][version] = "1.3"

projects[captcha][version] = "1.0"

projects[coffee][version] = "2.0"

projects[colorbox][version] = "2.5"

projects[commentsblock][version] = "2.3"

projects[context][version] = "3.1"

projects[custom_breadcrumbs][version] = "2.0-alpha3"

projects[date][version] = "2.7"

projects[devel][version] = "1.3"

projects[devel_themer][version] = "1.x-dev"

projects[diff][version] = "3.2"

projects[easy_social][version] = "2.10"

projects[elements][version] = "1.4"

projects[entity][version] = "1.3"

projects[entity_autocomplete][version] = "1.0-beta3"

projects[features][version] = "2.0"

projects[fences][version] = "1.0"

projects[fitvids][version] = "1.14"

projects[globalredirect][version] = "1.5"

projects[htmLawed][version] = "3.2"

projects[html5_tools][version] = "1.2"

projects[image_caption][version] = "1.0-beta3"

projects[imce][version] = "1.8"

projects[imce_mkdir][version] = "1.0"

projects[imce_wysiwyg][version] = "1.0"

projects[jquery_update][version] = "2.3"

projects[libraries][version] = "2.1"

projects[menu_attributes][version] = "1.0-rc2"

projects[metatag][version] = "1.0-beta7"

projects[module_filter][version] = "1.8"

projects[node_export][version] = "3.0-rc3"

projects[options_element][version] = "1.10"

projects[pathauto][version] = "1.2"

projects[recaptcha][version] = "1.10"

projects[revisioning][version] = "1.6"

projects[save_draft][version] = "1.4"

projects[select_or_other][version] = "2.20"

projects[semanticviews][version] = "1.x-dev"

projects[simplehtmldom][version] = "1.12"

projects[superfish][version] = "1.9"

projects[taxonomy_display][version] = "1.1"

projects[taxonomy_menu][version] = "1.4"

projects[taxonomy_title][version] = "1.5"

projects[token][version] = "1.5"

projects[uuid][version] = "1.0-alpha5"

projects[variable][version] = "2.3"

projects[video_embed_field][version] = "2.0-beta5"

projects[views][version] = "3.7"

projects[views_boxes][version] = "1.0-beta8"

projects[views_responsive_grid][version] = "1.3"

projects[wysiwyg][version] = "2.2"

projects[wysiwyg_spellcheck][version] = "1.1"

projects[xmlsitemap][version] = "2.0-rc2"

; Profiles
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[responsive_starter][download][type] = "git"
projects[responsive_starter][download][url] = "https://friendlymachine@bitbucket.org/friendlymachine/prometheus-profile.git"
projects[responsive_starter][type] = "profile"


; Modules
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[features_context][download][type] = "git"
projects[features_context][download][url] = "https://friendlymachine@bitbucket.org/friendlymachine/features-context-module.git"
projects[features_context][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[features_menu][download][type] = "git"
projects[features_menu][download][url] = "https://friendlymachine@bitbucket.org/friendlymachine/sample-menus-module.git"
projects[features_menu][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[features_miscellaneous][download][type] = "git"
projects[features_miscellaneous][download][url] = "https://friendlymachine@bitbucket.org/friendlymachine/sample-misc-features.git"
projects[features_miscellaneous][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[features_sample_content][download][type] = "git"
projects[features_sample_content][download][url] = "https://friendlymachine@bitbucket.org/friendlymachine/sample-content-module.git"
projects[features_sample_content][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[features_views][download][type] = "git"
projects[features_views][download][url] = "https://friendlymachine@bitbucket.org/friendlymachine/sample-views-module.git"
projects[features_views][type] = "module"

; Themes
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[prometheus][download][type] = "git"
projects[prometheus][download][url] = "https://friendlymachine@bitbucket.org/friendlymachine/prometheus-theme.git"
projects[prometheus][type] = "theme"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[ckeditor][download][type] = "get"
libraries[ckeditor][download][url] = "http://download.cksource.com/CKEditor/CKEditor/CKEditor%204.2.3/ckeditor_4.2.3_standard.zip"
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[colorbox][download][type] = "get"
libraries[colorbox][download][url] = "https://github.com/jackmoore/colorbox/archive/1.x.zip"
libraries[colorbox][directory_name] = "colorbox"
libraries[colorbox][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[easing][download][type] = "get"
libraries[easing][download][url] = "http://gsgd.co.uk/sandbox/jquery/easing/jquery.easing.1.3.js"
libraries[easing][directory_name] = "easing"
libraries[easing][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[fitvids][download][type] = "get"
libraries[fitvids][download][url] = "https://raw.github.com/davatron5000/FitVids.js/master/jquery.fitvids.js"
libraries[fitvids][directory_name] = "fitvids"
libraries[fitvids][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[superfish][download][type] = "get"
libraries[superfish][download][url] = "https://github.com/mehrpadin/Superfish-for-Drupal/archive/1.x.zip"
libraries[superfish][directory_name] = "superfish"
libraries[superfish][type] = "library"

