<?php
// $Id$

/**
 * This module adds autocomplete='off' to user login forms.
 */

function disable_autocomplete_form_alter(&$form, $form_state, $form_id) {
  switch ($form_id) {
    case 'user_login_block':
    case 'user_login':
    // This bit adds the attribute to the form tag, which should cover Chrome, Opera, etc.
    $form['#attributes']['autocomplete'] = 'off';
      // adding the attribute to the field like this only seems to work with Firefox
      $form['name']['#attributes']['autocomplete'] = 'off';
      // add to password field
      $form['pass']['#attributes']['autocomplete'] = 'off';

      case 'user_profile_form':
        $form['#attributes']['autocomplete'] = 'off';
        // add to password fields
        $form['pass']['#attributes']['autocomplete'] = 'off';
        case 'user_register_form':
          $form['#attributes']['autocomplete'] = 'off';
      break;
  }
}
